package main.java.UI;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

/**
 * @author Edward
 * @version 2
 * @since December 1, 2021
 */
public class FileManager {
    private final String fileForThemes = "scores.txt"; // to store names and scores

    /**
     * Stores this user's name and score in scores.txt
     * <p>
     * The method imports values from scores.txt into ArrayList of Tuples
     * using getTopScores().
     * It scans the list to check if this user already achieved a higher
     * score. If so, nothing remains to be done.
     * It adds the name and score and then sorts the array using
     * sortTupleList(t).
     * Finally, it overrides scores.txt with the new list.
     * Each tuple is stored in a single line as name:score.
     *
     * @param name a string generated by GameState
     * @param score an integer generated by GameState
     */
    public void addScore(String name, int score) {
        ArrayList<Tuple> tuples;
        tuples = getTopScores();
        boolean isNotListed = true; // is this username on file?
        name = name.trim();
        // scan and update this username if on file with a lower score
        for (Tuple tuple : tuples) {
            if (tuple.getStr().equals(name)) {
                if (tuple.getNum() > score) {
                    return; // already has higher score
                } else {
                    tuple.setNum(score); // score updated
                    isNotListed = false;
                    break;
                }
            }
        }
        if (isNotListed) {
            tuples.add(new Tuple(name, score)); // added new username
        }
        // sort
        tuples = sortTupleList(tuples);
        try {
            // to store names and scores
            String fileForScores = "scores.txt";
            FileWriter fileWriter = new FileWriter(fileForScores, false);  //overrides file
            for (Tuple tuple : tuples) {
                fileWriter.write(tuple.getStr() + ":" + tuple.getNum() + "\n");
            }
            fileWriter.close();
        } catch (IOException e) {
            System.out.println("Error occurred while writing to scores.txt");
            e.printStackTrace();
        }
    }

    /**
     * Returns a list of tuples with names and scores from scores.txt.
     * <p>
     * It opens the text file and reads each line separately.
     * Each line is parsed based on the colon into an array of strings
     * A tuple is created and populated with the first string as the name
     * and the second string as an integer value.
     * Tuples are then added to the array and the array are returned.
     *
     * @return  an array list with tuples of names and scores.
     */
    public ArrayList<Tuple> getTopScores(){
        ArrayList<Tuple> tuples = new ArrayList<>();
        try {
            File file = new File("scores.txt");
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String[] tokens = scanner.nextLine().split(":");
                Tuple tuple = new Tuple(tokens[0], Integer.parseInt(tokens[1]));
                tuples.add(tuple);
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("Error occurred while reading scores.txt");
            e.printStackTrace();
        }
        // System.out.println();
        return tuples;
    }

    /**
     * Returns a formatted listing of top five scores.
     *
     * @return      "<html>1. Name score seconds<br>2. Name score ... </html>
     */
    public String topFive(){
        String output;
        ArrayList<Tuple> tuples = getTopScores();
        int limit = tuples.size();
        // only top five are needed
        if (limit > 5){
            limit = 5;
        }
        StringBuilder outputBuilder = new StringBuilder("<html>");
        for (int i = 0; i < limit; i++) {
            outputBuilder.append(i + 1).append(". ").append(tuples.get(i).getStr()).append(": ").append(tuples.get(i).getNum()).append(" seconds<br>");
        }
        output = outputBuilder.toString();
        output = output + "</html>";
        return output;
    }

    /**
     * Creates a new file named "name.txt" to store this username
     */
    public void createFile(){
        // to store this username
        String fileForName = "name.txt";
        File file = new File(fileForName);
        try {
            if (file.createNewFile()) {
                System.out.println("File created: " + file.getName());
            } else {
                System.out.println("File already exists.");
            }
        } catch (IOException e) {
            System.out.println("File access error occurred.");
            e.printStackTrace();
        }
    }

    /**
     * Returns an array list of tuples sorted by the second field
     * <p>
     * The input is a list of pairs, each pair consisting of a string
     * and an integer, representing a username and their top score.
     * Using double for loop and an empty array list called result,
     * it picks a tuple from the input array and inserts it into
     * the resulting array in front of the tuple with a lower score.
     * The resulting array is thus sorted from the highest to the lowest.
     * The algorithm adds the input tuple to the end of the resulting array
     * when a higher tuple cannot be found.
     *
     * @param tuples    an array list of tuples to be sorted by the second field
     * @return          an array list of tuples sorted in descending order
     */
    public ArrayList<Tuple> sortTupleList(ArrayList<Tuple> tuples){
        ArrayList<Tuple> result = new ArrayList<>();
        for (Tuple tuple : tuples) {
            if (result.isEmpty()) {
                result.add(tuple);
            } else {
                for (int j = 0; j < result.size(); j++) {
                    if (tuple.getNum() > result.get(j).getNum()) {
                        // System.out.println("greater");
                        result.add(j, tuple);
                        break;
                    } else if (j == result.size() - 1) {
                        //System.out.println("at the tail");
                        result.add(tuple);
                        break;
                    }
                }
            }
        }
        return result;
    }

    /**
     * Records the theme selected by user
     *
     * @param theme     String for the game background: light or dark
     */
    public void writeTheme(String theme){
        try {
            FileWriter fileWriter = new FileWriter("theme.txt");
            fileWriter.write(theme);
            fileWriter.close();
        } catch (IOException e) {
            System.out.println("Writing error occurred when writing to theme.txt.");
            e.printStackTrace();
        }
    }

    public String readTheme() throws IOException {
        StringBuilder text = new StringBuilder();
        try {
            File file = new File("theme.txt");
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                text.append(" ").append(scanner.nextLine());
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("Error occurred while reading theme.txt.");
            FileWriter fileWriter = new FileWriter("theme.txt");
            fileWriter.write("light");
            fileWriter.close();
            // e.printStackTrace();
        }
        return text.toString().trim();
    }

    /**
     * Creates an object with two elements: a string representing the name of
     * the user and an integer representing the user's score.
     */
    static class Tuple {
        String str;
        int num;
        public Tuple(String str, int num){
            this.str = str;
            this.num = num;
        }
        public String getStr(){return this.str;}
        public int getNum(){return this.num;}
        public void setStr(String str){this.str = str;}
        public void setNum(int num){this.num = num;}
    }
}